config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get '/', to: 'home#index'
  root 'home#index'

  resources :car_categories, only: [:index, :show]
  # resources :manufacturers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :manufacturers
  resources :car_models, only: [:index, :show, :new, :create]

  # get '/rentals/serach', to: 'rental#search'
  resources :rentals, only: %i[index show new create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
    # get 'start', on: :member
    # post 'init', on: :member
  end

  resources :customers, only: %i[index show] do
    get 'search', on: :collection
  end
  
  resources :subsidiaries, only: [:index, :shoow, :new, :create, :edit, :update]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end 

app/views/home/index.html.erb
<header>
  <h1>Rental Cars</h1>
  <h2>Bem vindo ao sistema de gestão de locação</h2>
</header>

<!-- Colocar todos esse no nav do layouts application -->
<%= link_to 'Categorias de Carros', car_categories_path %>
<%= link_to 'Fabricantes', manufacturers_path %>
<%= link_to 'Modelos de Carros', car_models_path %>
<%= link_to 'Clientes', customers_path %>
<!-- Colocar todos esse no nav do layouts application -->

<h3>Playground do I18n</h3>

<%= I18n.translate ('hello') %>
<br>
<%= I18n.localize(Time.zone.now)%>
<br>
<%= I18n.localize(Date.today)%>
<br>

<%= distance_of_time_in_words(12000)%>
<%= number_to_currency(990000)%>