config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get '/', to: 'home#index'
  root 'home#index'

  resources :car_categories, only: [:index, :show]
  # resources :manufacturers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :manufacturers
  resources :car_models, only: [:index, :show, :new, :create]

  # get '/rentals/serach', to: 'rental#search'
  resources :rentals, only: %i[index show new create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
    # get 'start', on: :member
    # post 'init', on: :member
  end

  resources :customers, only: %i[index show] do
    get 'search', on: :collection
  end
  
  resources :subsidiaries, only: [:index, :shoow, :new, :create, :edit, :update]
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :rentals

  scope :search, ->(query) {where('name LIKE ?', "%#{query}%")
                              .or(where(document: query))}
  # SAO IGUAIS 
  # def self.search(query)
  #   where('name LIKE ?', "%#{query}%")
  # end

  # Caso fosse dinamico e com muitas tabelas
  # SEARCH_TABLES = %w[name document]
  # def self.search
  #   SEARCH_TABLES.each
  # end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def search
    # byebug
    # @customers = Customer.where(name: params[:q])

    # desse jeito o like fica safe, por causa que ? proteje que passa outros comandos e tome exploit
    # @customers = Customer.where('name LIKE ?', "%#{params[:q]}%")
    @customers = Customer.search(params[:q])
    render :index
  end
end

app/views/customers/index.html.erb
<h1>Clientes</h1>
  <% # TODO: fazer um teste de index do customer %>

<%= form_with url: search_customers_path, method: :get do |f| %>
  <% # TODO: Por no I18n *.yml %>
  <%= f.label :q, 'Buscar' %>
  <%= f.search_field :q %>
  <%= f.submit 'Buscar' %>

<% end %>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Documento</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr id="customer-<%= customer.id %>">
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.document %></td>
        <td><%#= link_to 'Ver Detalhes', cm, id: "details-#{cm.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/show.html.erb
<%#= render @customer.rentals %>
<h3><%= Rental.model_name.human(count: 2)%></h3>
<table>
  <tr>
    <th><%= Rental.human_attribute_name(:code) %></th>
    <th><%= Rental.human_attribute_name(:start_date) %></th>
    <th><%= Rental.human_attribute_name(:end_date) %></th>
    <th><%= Rental.human_attribute_name(:car_category) %></th>
    <th><%= Rental.human_attribute_name(:status) %></th>
    <th>Ações</th>
  </tr>

  <% @customer.rentals.each do |rental| %>

  <tr id="rental-<%= rental.code %>">
    <td><%= rental.code %></td>
    <td><%= l rental.start_date %></td>
    <td><%= l rental.end_date %></td>
    <td><%= rental.car_category.name %></td>
    <td><%= Rental.human_attribute_name("status.#{rental.status}")  %></td>
    <td>
      <% if rental.scheduled? %>
        <%= link_to 'Iniciar', new_rental_car_rental_path(rental) %>
      <% end %>
    </td>
  </tr>

  <% end %>
</table>