config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get '/', to: 'home#index'
  root 'home#index'

  resources :car_categories, only: [:index, :show]
  # resources :manufacturers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :manufacturers
  resources :car_models, only: [:index, :show, :new, :create]

  # get '/rentals/serach', to: 'rental#search'
  resources :rentals, only: %i[index show new create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
    # get 'start', on: :member
    # post 'init', on: :member
  end

  resources :customers, only: %i[index show] do
    get 'search', on: :collection
  end
  
  resources :subsidiaries, only: [:index, :shoow, :new, :create, :edit, :update]
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  # validates :name, uniqueness: {message: 'Nome deve ser único'}, presence: {message: 'Nome não pode ficar em branco'}
  validates :name, uniqueness: {message: 'Nome deve ser único'}
  validates :name, presence: {message: 'Nome não pode ficar em branco'}
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: [:show, :edit, :update]

  def index
    @manufacturers = Manufacturer.all
  end

  def show
    # id = params[:id]
    # @manufacturer = Manufacturer.find(id)
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:notice] = 'Fabricante criado com sucesso'
      redirect_to @manufacturer
    else
      render new_manufacturer_path
    end
  end

  def edit
    # @manufacturer = Manufacturer.find(params[:id])
  end

  # PATCH ou PUT
  def update
    # @manufacturer = Manufacturer.find(params[:id])
    if @manufacturer.update(manufacturer_params)
      redirect_to @manufacturer
    else
      render :new
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.destroy
    redirect_to manufacturers_path
  end

  private

  def set_manufacturer
    @manufacturer = Manufacturer.find(params[:id])
  end

  def manufacturer_params
    params.require(:manufacturer).permit(:name)
  end
end

app/views/manufacturers/edit.html.erb
<h1>Editar <%= @manufacturer.name %></h1>

<% @manufacturer.errors.full_messages.each do |message| %>
  <p><%= message%></p>
<% end %>

<%= form_with(model: @manufacturer, local: true) do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/manufacturers/index.html.erb
<h1>Fabricantes</h1>

<%= link_to 'Registrar novo fabricante', new_manufacturer_path %>

<ul>
  <% @manufacturers.each do |m| %>
    
    <li><%= link_to m.name, m %></li>
  <% end %>

  <% if @manufacturers.empty? %>
    <p>Nenhum fabricante cadastrado</p>
  <% end %>

  <%= link_to 'Voltar', root_path%>
</ul>

app/views/manufacturers/new.html.erb
<h1>Registrar Fabricante </h1>

<% @manufacturer.errors.full_messages.each do |m| %>
  <p><%= m %></p>
<% end %>

<%# <%= form_for @manufacturer do |f| %>  
<%= form_with model: @manufacturer, local: true do |f| %> 
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/manufacturers/show.html.erb
<h1><%= @manufacturer.name%></h1>

<%= link_to 'Editar', edit_manufacturer_path(@manufacturer) %>
<%= link_to 'Apagar', manufacturer_path(id: @manufacturer.id), method: :delete %>
<%= link_to 'Voltar', manufacturers_path%>